services:
  # 1. Database
  db:
    image: postgres:15
    container_name: medcore_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: medcore_ai
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Node API (The Manager)
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=medcore_ai
      - PGHOST=db
      - AI_SERVICE_URL=http://ai-service:8000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=raed.hassaan@gmail.com
      - SMTP_PASS=${SMTP_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}

    depends_on:
      - db
      - ai-service
  # 3. Python AI (The Brain)
  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app # <--- This allows live Python updates!
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
      - CHROMA_COLLECTION_NAME=medical_documents
      - GROQ_MODEL=${GROQ_MODEL}
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2

  # 4. React Client (The Face)
  client:
    build: ./client
    command: npm run dev -- --host 
    ports:
      - "5173:80"
    volumes:
      - ./client:/app # <--- This allows live React updates!
      - /app/node_modules
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps file watching on some Linux systems

volumes:
  db_data: